name: "Deploy to the AWS"

on:
   workflow_dispatch:


jobs:
  Practice_of_YML:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: "Install dependencies"
        run: npm install

      - name: "Install pm2 globally"
        run: npm install pm2 -g

      - name: "Run the tests"
        run: npm test

      - name: "Deploy to aws "
        run: pm2 start server.js
