name: "deploy to aws"

on: workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: "Setup Node.js"
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Install dependencies"
        run: npm install

      - name: "Install pm2 Globally"
        run: npm install pm2 -g

      - name: "Run the tests"
        run: npm test

      - name: "Deploy to aws"
        run: pm2 start server.js
