name: "Deploy to the AWS"

on:
   workflow_dispatch:


jobs:
  Practice_of_YML:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Print current directory
        run: pwd

      - name: List files
        run: ls -al

      - name: Install dependencies
        run: npm install

      - name: Run the tests
        run: npm test
